# TODO: may be risky to use latest here (no other tags though)
from firedrakeproject/firedrake

USER root

# https://github.com/luisfpereira/FInAT
ADD firedrake /home/firedrake/firedrake/src/firedrake

# https://github.com/luisfpereira/FInAT
ADD FInAT /home/firedrake/firedrake/src/FInAT

# https://github.com/luisfpereira/ufl
ADD ufl /home/firedrake/firedrake/src/ufl

# https://github.com/luisfpereira/tsfc
ADD tsfc /home/firedrake/firedrake/src/tsfc

RUN bash -c ". /home/firedrake/firedrake/bin/activate && pip install notebook"

ENV PATH="/home/firedrake/firedrake/bin/:$PATH"

RUN mkdir notebooks

ENV JUPYTER_CONFIG_DIR="/home/firedrake/notebooks/.jupyter"
