# TODO: may be risky to use latest here (no other tags though)
from firedrakeproject/firedrake

USER root

# https://github.com/luisfpereira/FInAT/tree/gstats
ADD FInAT /home/firedrake/firedrake/src/FInAT

# https://github.com/luisfpereira/ufl/tree/gstats
ADD ufl /home/firedrake/firedrake/src/ufl

# https://github.com/luisfpereira/tsfc/tree/gstats
ADD tsfc /home/firedrake/firedrake/src/tsfc

RUN bash -c ". /home/firedrake/firedrake/bin/activate && pip install notebook"

ENV PATH="/home/firedrake/firedrake/bin/:$PATH"

RUN mkdir notebooks

ENV JUPYTER_CONFIG_DIR="/home/firedrake/notebooks/.jupyter"
