# TODO: may be risky to use latest here (no other tags though)
from firedrakeproject/firedrake

USER root

# https://github.com/luisfpereira/FInAT
ADD FInAT /home/firedrake/firedrake/src/FInAT

# https://github.com/luisfpereira/ufl
ADD ufl /home/firedrake/firedrake/src/ufl

# https://github.com/luisfpereira/tsfc
ADD tsfc /home/firedrake/firedrake/src/tsfc

WORKDIR /home/firedrake/firedrake/src/firedrake
RUN git config --global --add safe.directory /home/firedrake/firedrake/src/firedrake
RUN git checkout a015738dcbad8f1555b15623fe17875ae665e884
RUN git switch -c gstats